export default{
	//OAUTH
	TWITTER_CLIENT_ID: "GJBMinFlXJAF1jjuMbQBgHQQ7",


	ATTEMPT_LOGIN: "ATTEMPT_LOGIN",
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAILURE: "LOGIN_FAILURE",

	SET_STORAGE_TOKEN: "SET_STORAGE_TOKEN"

}